[greeter]
background=/usr/share/backgrounds/rios/rios-default.png
theme-name=RiOS-Dark
icon-theme-name=RiOS-WhiteSur
font-name=Sans 10
default-user-image=/usr/share/plymouth/themes/rios/logo.png
screensaver-timeout=0
