[greeter]
background=/usr/share/backgrounds/rios/rios-default.png
theme-name=Adwaita-dark
icon-theme-name=Papirus-Dark
font-name=Sans 10
default-user-image=/usr/share/plymouth/themes/rios/logo.png
screensaver-timeout=0
