[greeter]
background=/usr/share/backgrounds/ratanaos/ratanaos-default.png
theme-name=RatanaOS-Dark
icon-theme-name=RatanaOS-WhiteSur
font-name=Sans 10
default-user-image=/usr/share/plymouth/themes/ratanaos/logo.png
screensaver-timeout=0
