---
backend: apt
skip_if_no_change: true
operations:
  - remove:
      - 'live-boot'
      - 'live-boot-doc'
      - 'live-config'
      - 'live-config-doc'
      - 'live-config-systemd'
      - 'live-tools'
      - 'live-task-localisation'
      - 'live-task-recommended'
      - 'calamares'
      - 'calamares-settings-debian'
