[greeter]
# RatanaOS macOS Sequoia 2026 LightDM Greeter Theme
theme-name = WhiteSur-Dark
icon-theme-name = WhiteSur-dark
cursor-theme-name = WhiteSur-cursors
cursor-theme-size = 24
font-name = Cantarell 11
background = /usr/share/backgrounds/ratanaos/ratanaos-sequoia-dark.png
user-background = false
default-user-image = /usr/share/pixmaps/ratana-logo.png
xft-antialias = true
xft-dpi = 96
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %a, %b %d  %I:%M %p
position = 50%,center 50%,center
panel-position = top
