[Icon Theme]
Name=Hicolor
Comment=Default RiOS Fallback Icon Theme
Hidden=true
Directories=16x16/apps,16x16/places,24x24/apps,24x24/places,32x32/apps,32x32/places,48x48/apps,48x48/places,64x64/apps,64x64/places,128x128/apps,128x128/places,256x256/apps,256x256/places,512x512/apps,512x512/places,scalable/apps,scalable/places

[16x16/apps]
Size=16
Type=Threshold
Context=Applications

[16x16/places]
Size=16
Type=Threshold
Context=Places

[24x24/apps]
Size=24
Type=Threshold
Context=Applications

[24x24/places]
Size=24
Type=Threshold
Context=Places

[32x32/apps]
Size=32
Type=Threshold
Context=Applications

[32x32/places]
Size=32
Type=Threshold
Context=Places

[48x48/apps]
Size=48
Type=Threshold
Context=Applications

[48x48/places]
Size=48
Type=Threshold
Context=Places

[64x64/apps]
Size=64
Type=Threshold
Context=Applications

[64x64/places]
Size=64
Type=Threshold
Context=Places

[128x128/apps]
Size=128
Type=Threshold
Context=Applications

[128x128/places]
Size=128
Type=Threshold
Context=Places

[256x256/apps]
Size=256
Type=Threshold
Context=Applications

[256x256/places]
Size=256
Type=Threshold
Context=Places

[512x512/apps]
Size=512
Type=Threshold
Context=Applications

[512x512/places]
Size=512
Type=Threshold
Context=Places

[scalable/apps]
Size=512
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/places]
Size=512
MinSize=16
MaxSize=512
Type=Scalable
Context=Places
