---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-*"
img: "/boot/initrd.img-*"
fallback: "/boot/initrd.img-*"
timeout: "5"
grubInstall: "grub-install"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
