# ==============================================================================
# RiOS Pro-Audio Real-Time Scheduling Limits
# ==============================================================================
@audio   -  rtprio     95
@audio   -  memlock    unlimited
@audio   -  nice      -19
