#!/usr/bin/env python3
import os
import sys
import struct
import argparse
import tarfile

def validate_path(rel_path):
    if rel_path.startswith('/') or '..' in rel_path.split('/'):
        raise ValueError(f"Unsafe path detected in rootfs: '{rel_path}'")
    return rel_path

def pack_debian_rootfs(src_dir, tarball, output_bin, output_c):
    print(f"[BAKE-DEBIAN-ROOTFS] Preparing rootfs package...")
    
    files = []
    
    if tarball and os.path.exists(tarball):
        print(f"[BAKE-DEBIAN-ROOTFS] Extracting rootfs tarball from {tarball}...")
        tmp_extract = '/tmp/ratana_debian_tarball_extract'
        os.makedirs(tmp_extract, exist_ok=True)
        with tarfile.open(tarball, 'r:*') as tar:
            tar.extractall(path=tmp_extract)
        src_dir = tmp_extract

    if src_dir and os.path.exists(src_dir):
        for root, dirs, filenames in os.walk(src_dir):
            for f in filenames:
                full_p = os.path.join(root, f)
                rel_p = os.path.relpath(full_p, src_dir).replace('\\', '/')
                try:
                    rel_p = validate_path(rel_p)
                    files.append((rel_p, full_p))
                except ValueError as err:
                    print(f"  [WARN] Skipping unsafe file: {err}")
    
    if not files:
        print("[BAKE-DEBIAN-ROOTFS] Creating default minimal embedded Debian 12 rootfs structure...")
        tmp_default = '/tmp/ratana_debian_rootfs'
        os.makedirs(os.path.join(tmp_default, 'etc'), exist_ok=True)
        os.makedirs(os.path.join(tmp_default, 'bin'), exist_ok=True)
        os.makedirs(os.path.join(tmp_default, 'lib64'), exist_ok=True)
        
        with open(os.path.join(tmp_default, 'etc/debian_version'), 'w') as f:
            f.write("12.5 (bookworm)\n")
        with open(os.path.join(tmp_default, 'etc/os-release'), 'w') as f:
            f.write('PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"\nNAME="Debian GNU/Linux"\nVERSION_ID="12"\nID=debian\n')
        with open(os.path.join(tmp_default, 'bin/hello_linux'), 'w') as f:
            f.write("Embedded Minimal Linux Executable Placeholder\n")
            
        src_dir = tmp_default
        for root, dirs, filenames in os.walk(src_dir):
            for f in filenames:
                full_p = os.path.join(root, f)
                rel_p = os.path.relpath(full_p, src_dir).replace('\\', '/')
                files.append((rel_p, full_p))

    header_fmt = "<4sII" # Magic 'DEBF', Version, NumFiles
    magic = b"DEBF"
    version = 1
    num_files = len(files)
    
    entry_header_fmt = "<128sII" # Path, Size, Offset
    
    entries_data = bytearray()
    file_bodies = bytearray()
    
    current_offset = 0
    for rel_p, full_p in files:
        with open(full_p, 'rb') as f:
            content = f.read()
        
        size = len(content)
        path_bytes = rel_p.encode('utf-8')[:127]
        path_bytes = path_bytes.ljust(128, b'\0')
        
        entry = struct.pack(entry_header_fmt, path_bytes, size, current_offset)
        entries_data.extend(entry)
        
        file_bodies.extend(content)
        current_offset += size
        
        print(f"  + /system/debian/{rel_p} ({size} bytes)")
        
    full_binary = bytearray()
    full_binary.extend(struct.pack(header_fmt, magic, version, num_files))
    full_binary.extend(entries_data)
    full_binary.extend(file_bodies)
    
    if output_bin:
        os.makedirs(os.path.dirname(os.path.abspath(output_bin)), exist_ok=True)
        with open(output_bin, 'wb') as f:
            f.write(full_binary)
        print(f"[BAKE-DEBIAN-ROOTFS] Saved container image to {output_bin} ({len(full_binary)} bytes).")
        
    if output_c:
        os.makedirs(os.path.dirname(os.path.abspath(output_c)), exist_ok=True)
        with open(output_c, 'w') as f:
            f.write("/* Automatically generated by tools/bake_debian_rootfs.py */\n")
            f.write("#include <stddef.h>\n\n")
            f.write(f"const unsigned char debian_rootfs_img[{len(full_binary)}] = {{\n")
            for i in range(0, len(full_binary), 16):
                chunk = full_binary[i:i+16]
                hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
                f.write(f"    {hex_str},\n")
            f.write("};\n")
            f.write(f"const unsigned int debian_rootfs_img_len = {len(full_binary)};\n")
        print(f"[BAKE-DEBIAN-ROOTFS] Saved C array header to {output_c}.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="RatanaOS Debian Rootfs Container Builder")
    parser.add_argument('--rootfs', '-r', default='debian-rootfs', help="Path to unpacked rootfs directory")
    parser.add_argument('--tarball', '-t', default=None, help="Path to rootfs tarball (.tar.xz, .tar.gz)")
    parser.add_argument('--output', '-o', default='build/debian.img', help="Output container path (.img or .rpk)")
    parser.add_argument('--c-output', '-c', default='src/kernel/fs/debian_data.c', help="Output C source file")
    
    args = parser.parse_args()
    pack_debian_rootfs(args.rootfs, args.tarball, args.output, args.c_output)
