#!/usr/bin/env python3
import os
import sys
import struct

def pack_debian_rootfs(src_dir, output_bin, output_c):
    print(f"[BAKE-DEBIAN-ROOTFS] Packing rootfs from {src_dir} into {output_bin} and {output_c}...")
    
    files = []
    if os.path.exists(src_dir):
        for root, dirs, filenames in os.walk(src_dir):
            for f in filenames:
                full_p = os.path.join(root, f)
                rel_p = os.path.relpath(full_p, src_dir).replace('\\', '/')
                files.append((rel_p, full_p))
    
    if not files:
        print("[BAKE-DEBIAN-ROOTFS] Creating default minimal embedded Debian 12 rootfs structure...")
        os.makedirs('/tmp/ratana_debian_rootfs/etc', exist_ok=True)
        os.makedirs('/tmp/ratana_debian_rootfs/bin', exist_ok=True)
        os.makedirs('/tmp/ratana_debian_rootfs/lib64', exist_ok=True)
        
        with open('/tmp/ratana_debian_rootfs/etc/debian_version', 'w') as f:
            f.write("12.5 (bookworm)\n")
        with open('/tmp/ratana_debian_rootfs/etc/os-release', 'w') as f:
            f.write('PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"\nNAME="Debian GNU/Linux"\nVERSION_ID="12"\nID=debian\n')
        with open('/tmp/ratana_debian_rootfs/bin/hello_linux', 'w') as f:
            f.write("Embedded Minimal Linux Executable Placeholder\n")
            
        src_dir = '/tmp/ratana_debian_rootfs'
        for root, dirs, filenames in os.walk(src_dir):
            for f in filenames:
                full_p = os.path.join(root, f)
                rel_p = os.path.relpath(full_p, src_dir).replace('\\', '/')
                files.append((rel_p, full_p))

    header_fmt = "<4sII" # Magic 'DEBF', Version, NumFiles
    magic = b"DEBF"
    version = 1
    num_files = len(files)
    
    entry_header_fmt = "<128sII" # Path, Size, Offset
    
    entries_data = bytearray()
    file_bodies = bytearray()
    
    current_offset = 0
    for rel_p, full_p in files:
        with open(full_p, 'rb') as f:
            content = f.read()
        
        size = len(content)
        path_bytes = rel_p.encode('utf-8')[:127]
        path_bytes = path_bytes.ljust(128, b'\0')
        
        entry = struct.pack(entry_header_fmt, path_bytes, size, current_offset)
        entries_data.extend(entry)
        
        file_bodies.extend(content)
        current_offset += size
        
        print(f"  + /mnt/debian/{rel_p} ({size} bytes)")
        
    full_binary = bytearray()
    full_binary.extend(struct.pack(header_fmt, magic, version, num_files))
    full_binary.extend(entries_data)
    full_binary.extend(file_bodies)
    
    os.makedirs(os.path.dirname(output_bin), exist_ok=True)
    with open(output_bin, 'wb') as f:
        f.write(full_binary)
        
    os.makedirs(os.path.dirname(output_c), exist_ok=True)
    with open(output_c, 'w') as f:
        f.write("/* Automatically generated by tools/bake_debian_rootfs.py */\n")
        f.write("#include <stddef.h>\n\n")
        f.write(f"const unsigned char debian_rootfs_img[{len(full_binary)}] = {{\n")
        for i in range(0, len(full_binary), 16):
            chunk = full_binary[i:i+16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {hex_str},\n")
        f.write("};\n")
        f.write(f"const unsigned int debian_rootfs_img_len = {len(full_binary)};\n")

    print(f"[BAKE-DEBIAN-ROOTFS] Successfully generated {output_bin} ({len(full_binary)} bytes).")

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'debian-rootfs'
    out_bin = sys.argv[2] if len(sys.argv) > 2 else 'build/debian.img'
    out_c = sys.argv[3] if len(sys.argv) > 3 else 'src/kernel/fs/debian_data.c'
    pack_debian_rootfs(src, out_bin, out_c)
