#!/usr/bin/env python3
import subprocess
import os

def run(cmd):
    print(f"[BUILD-USER] {cmd}")
    res = subprocess.run(cmd, shell=True, check=True)
    return res

def bin_to_c_array(bin_path, var_name):
    with open(bin_path, 'rb') as f:
        data = f.read()
    
    lines = [f"unsigned int {var_name}_len = {len(data)};\n", f"unsigned char {var_name}[] = {{\n"]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_str},\n")
    lines.append("};\n\n")
    return "".join(lines)

def main():
    os.makedirs("build", exist_ok=True)
    
    # 1. Compile libc
    run("nasm -f elf64 src/libc/crt0.asm -o build/crt0.o")
    run("gcc -m64 -ffreestanding -O2 -Wall -Wextra -Isrc/libc/include -fno-pie -fno-stack-protector -fno-builtin -nostdlib -c src/libc/libc.c -o build/libc.o")
    
    # 2. Compile user apps
    apps = [
        ("src/user/init/init.c", "build/init.o", "build/init.elf", "build_init_elf"),
        ("src/user/hello/hello.c", "build/hello.o", "build/hello.elf", "build_hello_elf"),
        ("src/user/sh/sh.c", "build/sh.o", "build/sh.elf", "build_sh_elf"),
        ("src/user/ls/ls.c", "build/ls.o", "build/ls.elf", "build_ls_elf"),
        ("src/user/cat/cat.c", "build/cat.o", "build/cat.elf", "build_cat_elf"),
        ("src/user/echo/echo.c", "build/echo.o", "build/echo.elf", "build_echo_elf"),
        ("src/user/pwd/pwd.c", "build/pwd.o", "build/pwd.elf", "build_pwd_elf"),
        ("src/user/uname/uname.c", "build/uname.o", "build/uname.elf", "build_uname_elf"),
        ("src/user/touch/touch.c", "build/touch.o", "build/touch.elf", "build_touch_elf"),
        ("src/user/mkdir/mkdir.c", "build/mkdir.o", "build/mkdir.elf", "build_mkdir_elf"),
        ("src/user/rm/rm.c", "build/rm.o", "build/rm.elf", "build_rm_elf"),
        ("src/user/free/free.c", "build/free.o", "build/free.elf", "build_free_elf"),
        ("src/user/ps/ps.c", "build/ps.o", "build/ps.elf", "build_ps_elf"),
        ("src/user/date/date.c", "build/date.o", "build/date.elf", "build_date_elf"),
        ("src/user/clear/clear.c", "build/clear.o", "build/clear.elf", "build_clear_elf"),
        ("src/user/ratapkg/ratapkg.c", "build/ratapkg.o", "build/ratapkg.elf", "build_ratapkg_elf"),
        ("src/user/debimport/debimport.c", "build/debimport.o", "build/debimport.elf", "build_debimport_elf"),
        ("src/user/ip/ip.c", "build/ip.o", "build/ip.elf", "build_ip_elf"),
        ("src/user/ping/ping.c", "build/ping.o", "build/ping.elf", "build_ping_elf"),
        ("src/user/grep/grep.c", "build/grep.o", "build/grep.elf", "build_grep_elf"),
        ("src/user/head/head.c", "build/head.o", "build/head.elf", "build_head_elf"),
        ("src/user/tail/tail.c", "build/tail.o", "build/tail.elf", "build_tail_elf"),
        ("src/user/wc/wc.c", "build/wc.o", "build/wc.elf", "build_wc_elf"),
        ("src/user/sort/sort.c", "build/sort.o", "build/sort.elf", "build_sort_elf"),
        ("src/user/sleep/sleep.c", "build/sleep.o", "build/sleep.elf", "build_sleep_elf"),
        ("src/user/kill/kill.c", "build/kill.o", "build/kill.elf", "build_kill_elf"),
        ("src/user/env/env.c", "build/env.o", "build/env.elf", "build_env_elf"),
    ]
    
    for src, obj, elf, _ in apps:
        run(f"gcc -m64 -ffreestanding -O2 -Wall -Wextra -Isrc/libc/include -fno-pie -fno-stack-protector -fno-builtin -nostdlib -c {src} -o {obj}")
        run(f"ld -m elf_x86_64 -nostdlib build/crt0.o {obj} build/libc.o -o {elf}")
    
    # 3. Generate initramfs_data.c
    c_content = "/* Auto-generated by tools/build_user.py */\n\n"
    for _, _, elf, var_name in apps:
        c_content += bin_to_c_array(elf, var_name)
        
    with open("src/kernel/fs/initramfs_data.c", "w") as f:
        f.write(c_content)
        
    print("[BUILD-USER] Successfully generated src/kernel/fs/initramfs_data.c")

if __name__ == "__main__":
    main()
