# Plymouth script for RatanaOS
Window.SetBackgroundTopColor (0.10, 0.08, 0.07);
Window.SetBackgroundBottomColor (0.10, 0.08, 0.07);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX (Window.GetWidth()  / 2 - logo.image.GetWidth()  / 2);
logo.sprite.SetY (Window.GetHeight() / 2 - logo.image.GetHeight() / 2);

fun refresh_callback () {
  # Add pulsing animation logic here
}

Plymouth.SetRefreshFunction (refresh_callback);
